//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEOBOX.OSC.IM.PointOnLineRemover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEOBOX.OSC.IM.PointOnLineRemover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string CoordinateFile_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("CoordinateFile_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordinatendatei (*.json) | *.json.
        /// </summary>
        internal static string CoordinateFile_FileDialogFilter {
            get {
                return ResourceManager.GetString("CoordinateFile_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der JSON-Inhalt konnte nicht korrekt gelesen werden..
        /// </summary>
        internal static string CoordnateFile_WrongContentErrorMessage {
            get {
                return ResourceManager.GetString("CoordnateFile_WrongContentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein kein Job oder ein ungültiger Job für die Ausführung aktiv.
        ///Bitte zuerst ein Job im Status &quot;in Bearbeitung&quot; auswählen..
        /// </summary>
        internal static string DocumentPlugIn_JobIsNotReadyMessage {
            get {
                return ResourceManager.GetString("DocumentPlugIn_JobIsNotReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren.
        /// </summary>
        internal static string ExportMnuItem {
            get {
                return ResourceManager.GetString("ExportMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Funktion is nur im View-Modus verfügbar..
        /// </summary>
        internal static string FunctionOnlyInViewMode {
            get {
                return ResourceManager.GetString("FunctionOnlyInViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Punkt Tools.
        /// </summary>
        internal static string genModulName {
            get {
                return ResourceManager.GetString("genModulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordinate [{0}/{1}] ist der Endpunkt der Linie [{2}]. Die Linie wurde nicht geändert..
        /// </summary>
        internal static string LinePoint_EndPoint_Message {
            get {
                return ResourceManager.GetString("LinePoint_EndPoint_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordinate [{0}/{1}] ist der Startpunkt der Linie [{2}]. Die Linie wurde nicht geändert..
        /// </summary>
        internal static string LinePoint_StartPoint_Message {
            get {
                return ResourceManager.GetString("LinePoint_StartPoint_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordinate [{0}/{1}] wurde als Stützpunkt aus der Linie [{2}] entfernt..
        /// </summary>
        internal static string LinePoint_SuccesRemoved_Message {
            get {
                return ResourceManager.GetString("LinePoint_SuccesRemoved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .log.
        /// </summary>
        internal static string LogFile_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("LogFile_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokolldatei (*.log) | *.log | Text-Datei (*.txt) | *.txt | Alle Dateien (*.*) | *.*.
        /// </summary>
        internal static string LogFile_FileDialogFilter {
            get {
                return ResourceManager.GetString("LogFile_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool um Stützpunkte und Punkte anhand einer Koordinate zu entfernen..
        /// </summary>
        internal static string LoggerComment {
            get {
                return ResourceManager.GetString("LoggerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektklasse &apos;{0}&apos; [{1} es wurden {2} Objekte gefunden, {3} wurden geändert..
        /// </summary>
        internal static string LogMessage_EndFeatureClass {
            get {
                return ResourceManager.GetString("LogMessage_EndFeatureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektklasse &apos;{0}&apos; [{1}] wird bearbeitet..
        /// </summary>
        internal static string LogMessage_HandleFeatureClass_Start {
            get {
                return ResourceManager.GetString("LogMessage_HandleFeatureClass_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Linien-Objektklassen für das Entfernen ausgewählt..
        /// </summary>
        internal static string LogMessage_NoLineClassesSelected {
            get {
                return ResourceManager.GetString("LogMessage_NoLineClassesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Punkt-Objektklassen für das Entfernen ausgewählt..
        /// </summary>
        internal static string LogMessage_NoPointClassesSelected {
            get {
                return ResourceManager.GetString("LogMessage_NoPointClassesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Koordinaten wurden aus der folgenden Datei gelesen.
        /// </summary>
        internal static string LogMessage_SelectedCoodianteFile {
            get {
                return ResourceManager.GetString("LogMessage_SelectedCoodianteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektklasse &apos;{0}&apos; [{1} wird bearbeitet..
        /// </summary>
        internal static string LogMessage_StartFeatureClass {
            get {
                return ResourceManager.GetString("LogMessage_StartFeatureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Punkte entfernen aus Linien-Objektklassen....
        /// </summary>
        internal static string LogMessage_StartRemoveFromLineClasses {
            get {
                return ResourceManager.GetString("LogMessage_StartRemoveFromLineClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Punkte entfernen aus Punkt-Objektklassen....
        /// </summary>
        internal static string LogMessage_StartRemoveFromPointClasses {
            get {
                return ResourceManager.GetString("LogMessage_StartRemoveFromPointClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim Speichern der Objekte &apos;{0}&apos; [{1}]. Meldung:
        ///{2}.
        /// </summary>
        internal static string LogMessage_UpdateFeature_Error {
            get {
                return ResourceManager.GetString("LogMessage_UpdateFeature_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Punkt Tools.
        /// </summary>
        internal static string MapContextMenue_PointToolsRoot {
            get {
                return ResourceManager.GetString("MapContextMenue_PointToolsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte entfernen (mit Liste).
        /// </summary>
        internal static string MapContextMenue_RemovePointsWithList {
            get {
                return ResourceManager.GetString("MapContextMenue_RemovePointsWithList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte konnten Erfolgreich entfernt werden. Details finden Sie in der Protokolldatei..
        /// </summary>
        internal static string PointRemoverViewModel_RemovePointsSuccess {
            get {
                return ResourceManager.GetString("PointRemoverViewModel_RemovePointsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte konnten nicht ohne Meldung entfernt werden. Kontrollieren Sie die Protokolldatei!.
        /// </summary>
        internal static string PointRemoverViewModel_RemovePointsWithWarnings {
            get {
                return ResourceManager.GetString("PointRemoverViewModel_RemovePointsWithWarnings", resourceCulture);
            }
        }
    }
}
