//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEOBOX.OSC.IM.PointOnLineRemover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEOBOX.OSC.IM.PointOnLineRemover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string CoordinateFile_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("CoordinateFile_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordinatendatei (*.json) | *.json.
        /// </summary>
        internal static string CoordinateFile_FileDialogFilter {
            get {
                return ResourceManager.GetString("CoordinateFile_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefilterte Objekte zur Liste hinzufügen.
        /// </summary>
        internal static string DlgPlugIn_AddFilterToListMenuTitle {
            get {
                return ResourceManager.GetString("DlgPlugIn_AddFilterToListMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt zur Liste hinzufügen.
        /// </summary>
        internal static string DlgPlugIn_AddObjectToListMenuTitle {
            get {
                return ResourceManager.GetString("DlgPlugIn_AddObjectToListMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Objekt wurde zur Liste hinzugefügt..
        /// </summary>
        internal static string DlgPlugIn_FeatureAddedToListMessage {
            get {
                return ResourceManager.GetString("DlgPlugIn_FeatureAddedToListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Objekte wurden zur Liste hinzugefügt..
        /// </summary>
        internal static string DlgPlugIn_FeaturesAddedToListMessage {
            get {
                return ResourceManager.GetString("DlgPlugIn_FeaturesAddedToListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KML-Export.
        /// </summary>
        internal static string DlgPlugIn_KMLMenuTitle {
            get {
                return ResourceManager.GetString("DlgPlugIn_KMLMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne Liste.
        /// </summary>
        internal static string DlgPlugIn_OpenListTableMenuTitle {
            get {
                return ResourceManager.GetString("DlgPlugIn_OpenListTableMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren.
        /// </summary>
        internal static string ExportMnuItem {
            get {
                return ResourceManager.GetString("ExportMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Funktion is nur im View-Modus verfügbar..
        /// </summary>
        internal static string FunctionOnlyInViewMode {
            get {
                return ResourceManager.GetString("FunctionOnlyInViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Punkt Tools.
        /// </summary>
        internal static string genModulName {
            get {
                return ResourceManager.GetString("genModulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .log.
        /// </summary>
        internal static string LogFile_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("LogFile_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokolldatei (*.log) | *.log | Text-Datei (*.txt) | *.txt | Alle Dateien (*.*) | *.*.
        /// </summary>
        internal static string LogFile_FileDialogFilter {
            get {
                return ResourceManager.GetString("LogFile_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool um Stützpunkte und Punkte anhand einer Koordinate zu entfernen..
        /// </summary>
        internal static string LoggerComment {
            get {
                return ResourceManager.GetString("LoggerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Punkt Tools.
        /// </summary>
        internal static string MapContextMenue_PointToolsRoot {
            get {
                return ResourceManager.GetString("MapContextMenue_PointToolsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte entfernen (mit Liste).
        /// </summary>
        internal static string MapContextMenue_RemovePointsWithList {
            get {
                return ResourceManager.GetString("MapContextMenue_RemovePointsWithList", resourceCulture);
            }
        }
    }
}
